
platform :ios, '12.1'

target 'Example' do
  use_frameworks!

  pod "Kingfisher", "~> 5.0.0"
  pod "SwiftShell", ">= 4.0.0"

  pod "Tyler", :git => "https://github.com/IgorMuzyka/Tyler.git"
  pod "Identifier", :git => "https://github.com/IgorMuzyka/Tyler.Identifier.git"
  pod "Tag", :git => "https://github.com/IgorMuzyka/Tyler.Tag.git"
  pod "Variable", :git => "https://github.com/IgorMuzyka/Tyler.Variable.git"
  pod "Style", :git => "https://github.com/IgorMuzyka/Tyler.Style.git"
  pod "Anchor", :git => "https://github.com/IgorMuzyka/Tyler.Anchor.git"
  pod "Action", :git => "https://github.com/IgorMuzyka/Tyler.Action.git"

  pod "Substitutes", :git => "https://github.com/IgorMuzyka/Tyler.Substitutes.git"
  pod "TylerSupportAppleCommon", :git => "https://github.com/IgorMuzyka/Tyler.Support.Apple.Common.git"
  pod "TylerSupportAppleUIKit", :git => "https://github.com/IgorMuzyka/Tyler.Support.Apple.UIKit.git"
  pod "TypePreservingCodingAdapter", :git => "https://github.com/IgorMuzyka/Type-Preserving-Coding-Adapter.git"

	pod "SharedTiles", :git => "https://github.com/IgorMuzyka/Tyler.Example.Shared.Tiles.git"

end

